# Generated by Django 4.1.7 on 2023-04-01 15:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
