# Generated by Django 4.1.7 on 2023-03-28 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='verify',
            field=models.BooleanField(default=False),
        ),
    ]
